DROP FUNCTION run3pgModel(lengthOfGrowth integer);
DROP FUNCTION Intcptn("MaxIntcptn" float, "cur_LAI" float, "LAImaxIntcptn" float);
DROP FUNCTION init_Intcptn("MaxIntcptn" float, "cur_LAI" float, "LAImaxIntcptn" float);
DROP FUNCTION ASW("maxASW" float, "prev_ASW" float, "date_ppt" float, "cur_Transp" float, "cur_Intcptn" float, "cur_Irrig" float);
DROP FUNCTION init_ASW("maxAWS" float);
DROP FUNCTION VPD("date_tmin" float, "date_tmax" float, "date_tdmean" float);
DROP FUNCTION fVPD("kG" float, "cur_VPD" float);
DROP FUNCTION fFrost("date_tmin" float);
DROP FUNCTION fT("date_tmin" float, "date_tmax" float, "Tmin" float, "Tmax" float, "Topt" float);
DROP FUNCTION Irrig("irrigFrac" float, "cur_Transp" float, "cur_Intcptn" float, "date_ppt" float);
DROP FUNCTION CumIrrig("prev_CumIrrig" float, "cur_Irrig" float);
DROP FUNCTION init_CumIrrig();
DROP FUNCTION fAge("prev_StandAge" float, "maxAge" float, "rAge" float, "nAge" float);
DROP FUNCTION init_fAge("cur_StandAge" float, "maxAge" float, "rAge" float, "nAge" float);
DROP FUNCTION fSW("prev_ASW" float, "maxAWS" float, "swconst" float, "swpower" float);
DROP FUNCTION init_fSW("cur_ASW" float, "maxAWS" float, "swconst" float, "swpower" float);
DROP FUNCTION fNutr("fN0" float, "FR" float);
DROP FUNCTION PhysMod("cur_fVPD" float, "cur_fSW" float, "cur_fAge" float);
DROP FUNCTION LAI("prev_WF" float, "SLA1" float, "SLA0" float, "prev_StandAge" float, "tSLA" float);
DROP FUNCTION init_LAI("cur_WF" float, "SLA1" float, "SLA0" float, "cur_StandAge" float, "tSLA" float);
DROP FUNCTION CanCond("MaxCond" float, "cur_PhysMod" float, "cur_LAI" float, "LAIgcx" float);
DROP FUNCTION Transp("days_per_mon" float, "e20" float, "Qa" float, "Qb" float, "date_nrel" float, "date_daylight" float, "rhoAir" float, "lambda" float, "VPDconv" float, "cur_VPD" float, "BLcond" float, "cur_CanCond" float);
DROP FUNCTION NPP("prev_StandAge" float, "fullCanAge" float, "cur_xPP" float, "k" float, "prev_LAI" float, "cur_fVPD" float, "cur_fSW" float, "cur_fAge" float, "alpha" float, "fNutr" float, "cur_fT" float, "cur_fFrost" float);
DROP FUNCTION init_NPP("cur_StandAge" float, "fullCanAge" float, "cur_xPP" float, "k" float, "cur_LAI" float, "cur_fVPD" float, "cur_fSW" float, "cur_fAge" float, "alpha" float, "fNutr" float, "cur_fT" float, "cur_fFrost" float);
DROP FUNCTION litterfall("gammaFx" float, "gammaF0" float, "prev_StandAge" float, "tgammaF" float, "prev_lastCoppiceAge" float);
DROP FUNCTION init_litterfall("gammaFx" float, "gammaF0" float, "cur_StandAge" float, "tgammaF" float);
DROP FUNCTION pS("prev_WS" float, "StockingDensity" float, "StemConst" float, "StemPower" float, "cur_pR" float, "pfsConst" float, "pfsPower" float);
DROP FUNCTION init_pS("cur_WS" float, "StockingDensity" float, "StemConst" float, "StemPower" float, "cur_pR" float, "pfsConst" float, "pfsPower" float);
DROP FUNCTION pR("pRx" float, "pRn" float, "cur_PhysMod" float, "m0" float, "FR" float);
DROP FUNCTION pF("cur_pR" float, "cur_pS" float);
DROP FUNCTION WF("cur_pF" float, "prev_WF" float, "cur_NPP" float, "cur_litterfall" float);
DROP FUNCTION init_WF("StockingDensity" float, "SeedlingMass" float);
DROP FUNCTION WR("prev_WR" float, "cur_NPP" float, "cur_pR" float, "Rttover" float);
DROP FUNCTION init_WR("StockingDensity" float, "SeedlingMass" float);
DROP FUNCTION WS("prev_WS" float, "cur_NPP" float, "cur_pS" float);
DROP FUNCTION init_WS("StockingDensity" float, "SeedlingMass" float);
DROP FUNCTION W("cur_WF" float, "cur_WR" float, "cur_WS" float);
DROP FUNCTION StandAge("prev_StandAge" float);
DROP FUNCTION init_StandAge();
DROP FUNCTION PAR("date_rad" float, "molPAR_MJ" float);
DROP FUNCTION xPP("y" float, "cur_PAR" float, "gDM_mol" float);
DROP FUNCTION coppice_pfs("prev_WS" float, "StockingDensity" float, "cpStemsPerStump" float, "cpStemConst" float, "cpStemPower" float, "cpPfsConst" float, "cpPfsPower" float, "cpMaxPfs" float);
DROP FUNCTION coppice_pS("cur_pR" float, "pfs" float);
DROP FUNCTION coppice_pF("cur_pR" float, "pfs" float);
DROP FUNCTION coppice_RootPP("cur_npp" float, "cur_nppTarget" float, "WR" float, "W" float, "pRx" float, "cpRootStoragePct" float, "cpRootLAITarget" float);
DROP FUNCTION coppice_NPP("cur_npp" float, "coppice_RootPP" float);
DROP FUNCTION coppice_WR("prev_WR" float, "cur_NPP" float, "cur_pR" float, "Rttover" float, "coppice_RootPP" float);
DROP TYPE weather;
DROP TYPE soil;
DROP TYPE plantation_state;
DROP TYPE tree CASCADE;
DROP TYPE constants;
DROP TABLE IF EXISTS trees;
